Add bookings
Rexsus-bit/java-shareit pull request #5
Opened 2022-08-14 18:20 UTC by Rexsus-bit

2022-08-23 21:52 UTC, Fleaman777 requested changes

2022-08-23 21:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/booking/BookingController.java
> +    public BookingDTO createBooking(@RequestHeader("X-Sharer-User-Id") long userId, @RequestBody @NonNull @Valid BookingDTO bookingDTO) {
X-Sharer-User-Id можно вынести в константу, 
и использовать ее в местах, где используется X-Sharer-User-Id

2022-08-23 21:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/booking/BookingLinksDTO.java
> +    Long bookerId;
поля должны быть private

2022-08-23 21:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/item/Item.java
> +    }
а почему решил явно задать констурктор, а не через ломбок аннотацию ?

2022-08-23 21:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/item/ItemService.java
> +                .collect(Collectors.toList())));
стрим можно не передавать в конструктор new HashSet<>, а сразу стрим собрать в HashSet вместо листа

2022-08-23 21:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/item/ItemService.java
> +        return itemsDTO.stream().sorted(Comparator.comparingLong(ItemDTO::getId)).collect(
длинные методы плохо вспринимаются, 
попробуй его уменьшить, за счет выноса части логики в отдельные методы

2022-08-23 21:52 UTC, Fleaman777 commented on src/main/resources/schema.sql
> +DROP table IF EXISTS users, items, bookings, comments;
а точно ли нужен этот запрос ? 

каждый раз когда приложение будет стартовать, оно будет удалять все таблицы, в которых могли быть какие-то данные

2022-08-23 21:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/booking/BookingService.java
> +                || booking.getEnd().isBefore(LocalDateTime.now()))
LocalDateTime.now() можно вынести в локальную переменную

2022-08-23 21:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/booking/BookingService.java
> +                return bookingRepository.findAllByBookerIdAndEndBeforeOrderByStartDesc(userId, LocalDateTime.now());
здесть тоже LocalDateTime.now() можно вынести в локальную переменную

2022-08-23 21:52 UTC, Fleaman777 commented on src/main/java/ru/practicum/booking/BookingService.java
> +                return bookingRepository.findAllByItemOwnerIdAndEndBeforeOrderByStartDesc(userId, LocalDateTime.now());
аналагично комменту выше

2022-08-23 22:02 UTC, Rexsus-bit commented on src/main/java/ru/practicum/item/ItemService.java
> +                .collect(Collectors.toList())));
Оставил только конструктор без аргументов. Он нужен т.к. иначе будет доступен только непубличный конструктор, создаваемый аннотацией @Builder

2022-08-23 22:07 UTC, Rexsus-bit commented on src/main/resources/schema.sql
> +DROP table IF EXISTS users, items, bookings, comments;
Да, иначе не будет нумерация сбрасываться айдишников

2022-08-24 16:43 UTC, Fleaman777 approved these changes

2022-08-24 16:43 UTC, Fleaman777 commented on src/main/java/ru/practicum/booking/BookingController.java
> +    private final String HEADER = "X-Sharer-User-Id";
можно чуть более говорящее название, например, USER_ID_HEADER

2022-08-24 16:43 UTC, Fleaman777 commented on src/main/java/ru/practicum/booking/BookingController.java
> +    private final String header = "X-Sharer-User-Id";
это вполне себе константа

2022-08-29 10:36 UTC, merged