Add docker
Rexsus-bit/java-shareit pull request #8
Opened 2022-09-20 12:09 UTC by Rexsus-bit

2022-09-21 15:09 UTC, Fleaman777 requested changes

2022-09-21 15:09 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String header = "X-Sharer-User-Id";
здесь тоже в верхнем регистре

2022-09-21 15:09 UTC, Fleaman777 commented on server/src/main/resources/application.properties
> +#spring.datasource.password=${POSTGRES_PASSWORD}
сейчас получается, что значения переменных окружения, используются те, которые указаны в application.properties, а не те, которые в docker-compose 

например,
можно использовать такую конструкцию: `spring.datasource.username=${POSTGRES_USER:test}`
она означает, что если, в докер-компосе не просетать переменную POSTGRES_USER, то будет использоваться дефлотное значение test

2022-09-21 19:23 UTC, Rexsus-bit commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	private static final String header = "X-Sharer-User-Id";
Чек стайл встроенный тогда не проходит, а так согласен

2022-09-21 19:23 UTC, Rexsus-bit commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private static final String header = "X-Sharer-User-Id";
см. коммент выше

2022-09-21 19:41 UTC, Rexsus-bit commented on server/src/main/resources/application.properties
> +#spring.datasource.password=${POSTGRES_PASSWORD}
спасибо, познавательно! Переключил данные на переменные окружения

2022-09-22 19:38 UTC, Fleaman777 approved these changes

2022-09-22 19:38 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	private static final String header = "X-Sharer-User-Id";
хм, интересный чекстайл)
окй, понял

2022-09-22 19:38 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
>  											   @PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
можно удалить параметр name, 
без него тоже должно все работать и будет выглядеть чуть чище

2023-01-09 13:39 UTC, merged